### ISSUE TITLE
Add feature in Transactions to make addresses or txn hash copy clickable

### ISSUE THREAD

**Issue by TheStophe** [Satergo/Satergo#20]
Would be a nice feature enhancement for the Transactions tab that the wallet addr or txn hash make it:
- clickable to copy
- or just open up into the ergo explorer

**Comment by satsen** [comment]
Wallet addresses in the transaction history can be copied by simply right clicking them and selecting "Copy" (or "Copy address", seems like I've implemented it in 2 locations by accident - one on the address text and one on the input/output row itself).

I have missed to implement the same for transaction IDs however so that will be added in the next release.

**Comment by TheStophe** [comment]
Ah I see, thanks. Maybe a little "copy" icon to the right would make it more obvious. I enlarged the screen and right clicked, I see the copy pop-up now. Idk, people might like just a hot link for all of the addr or txns to ergo explorer. Or have a goto link to ergo explorer at the bottom. But it's subjective for sure.
